name: Hello on Push or PR to Master

on:
  push:
    branches:
      - master  # Trigger on push to 'master'
  pull_request:
    branches:
      - master  # Trigger when a PR targets 'master'

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type and branch
        run: echo "Hello from GitHub Actions! Triggered by a ${{ Hi-app }} to master."



   